### ISSUE TITLE
Schedule Toggle Issue

### ISSUE THREAD

**Issue by blueliquiddesigns** [stevehenty/gravityflow#1]
When you enable the "Schedule" option when setting up a Workflow and then select a "Step Type" (or change the type) the toggle remains enabled but doesn't show the Delay/Date settings. Instead, the "Schedule" toggle functions in reverse – disabled shows the Delay/Date options and enabled does not.

**Comment by stevehenty** [comment]
Thanks Jake! Fixed in 1.1.1.4.
